version: '3.8'

services:


  mysql-album:
    image: mysql:latest
    pull_policy: always
    ports:
      - 3307:3306
    volumes:
      - mysql_album_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123


  mysql-winkel:
    image: mysql:latest
    pull_policy: always
    ports:
      - 3309:3306
    volumes:
      - mysql_winkel_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123


  mongo-artiest:
    image: mongo:latest
    pull_policy: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_artiest_data:/data/db

  artiest-service:
    depends_on:
      - mongo-artiest
    image: nielswusten/artiest-service
    pull_policy: always
    ports:
      - 8081:8081
    volumes:
      - mongodb_artiest_data:/data/db
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-artiest

  album-service:
    depends_on:
      - mysql-album
    image: nielswusten/album-service
    pull_policy: always
    ports:
      - 8082:8082
    volumes:
      - mysql_album_data:/var/lib/mysql
    environment:
      MYSQL_DB_HOST: mysql-album
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123

  winkel-service:
    depends_on:
      - mysql-winkel
    image: nielswusten/winkel-service
    pull_policy: always
    ports:
      - 8083:8083
    volumes:
      - mysql_winkel_data:/var/lib/mysql
    environment:
      MYSQL_DB_HOST: mysql-winkel
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123


  api-gateway:
    image: nielswusten/api-gateway
    pull_policy: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - artiest-service
      - album-service
      - winkel-service
    environment:
      ARTIEST_SERVICE_BASEURL: artiest-service:8081
      ALBUM_SERVICE_BASEURL: album-service:8082
      WINKEL_SERVICE_BASEURL: winkel-service:8083

  frontend:
    image: nielswusten/frontend:latest
    build:
      context: ./react-frontend/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_GATEWAY_URL: http://api-gateway:8080
    ports:
      - 3000:80
    depends_on:
      - api-gateway
    environment:
      REACT_APP_API_GATEWAY_URL: http://api-gateway:8080

#test

volumes:
    mysql_album_data:
    mongodb_artiest_data:
    mysql_winkel_data:



