  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 390971080892-aq334h72jejri8gl34jt6qaalrr9497i.apps.googleusercontent.com
              client-secret: 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
              scope: openid,profile,email
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
    cloud:
      gateway:
        routes:
          - id: winkel-service-get-all
            uri: http://winkel-service:8083
            predicates:
              - Path=/winkel
              - Method=GET
            filters:
              - SetPath=/api/winkel
          - id: winkel-service-get-by-id
            uri: http://winkel-service:8083
            predicates:
              - Path=/winkel/{id}
              - Method=GET
            filters:
              - SetPath=/api/winkel/{id}
          - id: winkel-service-post
            uri: http://winkel-service:8083
            predicates:
              - Path=/winkel
              - Method=POST
            filters:
              - SetPath=/api/winkel

