  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 390971080892-aq334h72jejri8gl34jt6qaalrr9497i.apps.googleusercontent.com
              client-secret: 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
              scope: openid,profile,email
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
    cloud:
      gateway:
        routes:
          - id: artiest-service
            uri: http://artiest-service:8081
            predicates:
              - Path=artiest/**
          - id: album-service
            uri: http://album-service:8082
            predicates:
              - Path=/album/**
          - id: winkel-service
            uri: http://winkel-service:8083
            predicates:
              - Path=/winkel/**
